/* eslint-disable no-unused-vars */
export enum QueryKeysProduct {
  GET_ALL_PRODUCT = "GET_ALL_PRODUCT",
  GET_BEST_SELLER = "GET_BEST_SELLER",
  GET_DETAIL_PRODUCT = "GET_DETAIL_PRODUCT",
  GET_PRODUCT_CATEGORY = "GET_PRODUCT_CATEGORY",
  GET_PRODUCT_BRAND = "GET_PRODUCT_BRAND",
  GET_PRODUCT_SUPPLIER = "GET_PRODUCT_SUPPLIER",
  GET_PRODUCT_SEARCH = "GET_PRODUCT_SEARCH",
}
